spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: library-service
  profiles:
    active: default
  zipkin:
    base-url: http://localhost:9411

server:
#  port: 8090
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
  client:
    #    fetch-registry: true
    #    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
