spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/v1/books/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/libraries/**
      discovery:
        locator:
          enabled: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
