spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: book-service
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
#    fetch-registry: true
#    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
